bump_version: null
lint:
    multiqc_config: false
    files_exist:
        - conf/igenomes.config
        - conf/igenomes_ignored.config
        - assets/multiqc_config.yml
nf_core_version: 3.2.0
org_path: null
repository_type: pipeline
template:
    author: Jin Yan Khoo
    description: Extract methylation calls from long reads
    force: true
    is_nfcore: true
    name: methylong
    org: nf-core
    outdir: .
    skip_features:
        - igenomes
        - fastqc
        - multiqc
    version: 1.0.0dev
update: null
