lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
  nextflow_config:
    - config_defaults:
        - params.ccsmeth_cm_model
        - params.ccsmeth_ag_model
  template_strings: false
nf_test_content: false
nf_core_version: 3.4.1
repository_type: pipeline
template:
  author: Jin Yan Khoo, Yi Jin Xiong
  description: Extract methylation calls from long reads
  force: false
  is_nfcore: true
  name: methylong
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
  version: 2.0.0