bump_version:
lint:
  files_exist:
    - conf/igenomes.config
    - conf/igenomes_ignored.config
nf_core_version: 3.2.0
repository_type: pipeline
template:
  author: Jin Yan Khoo
  description: Extract methylation calls from long reads
  force: true
  is_nfcore: true
  name: methylong
  org: nf-core
  outdir: .
  skip_features:
    - igenomes
  version: 1.0.0
