repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.1.0"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5

  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: "3.0.3"
    hooks:
      - id: editorconfig-checker
        alias: ec

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: |
          ^modules/nf-core/samtools/fastq/main.nf$
          ^modules/nf-core/porechop/porechop/main.nf$
          ^subworkflows/nf-core/utils_nfschema_plugin/main.nf$
