contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #methylong channel"
    url: https://nfcore.slack.com/channels/methylong
    about: Discussion about the nf-core/methylong pipeline
